apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-info-web
  labels:
    app: health-info
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-info
      tier: backend
  template:
    metadata:
      labels:
        app: health-info
        tier: backend
    spec:
      containers:
      - name: web
        image: njange/health-info-system:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: DJANGO_SETTINGS_MODULE
          value: "health_system.settings"
        - name: DATABASE_URL
          value: "postgres://postgres:password@health-info-db:5432/health_db"
        - name: DJANGO_ALLOWED_HOSTS
          value: "localhost,127.0.0.1"
        volumeMounts:
        - name: static-files
          mountPath: /app/staticfiles
      volumes:
      - name: static-files
        emptyDir: {}