apiVersion: v1
kind: Service
metadata:
  name: health-info-web
spec:
  selector:
    app: health-info
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer